### ISSUE TITLE
The cursor position Breaks the Markdown representation

### ISSUE THREAD

**Issue by seaspeak** [efreykongcn/NoteWidget#1]
1. Open a new OneNote page.
2. Type in `This is the **test**`
3. Move the cursor to the circumflex position `This is the *^*test**`
4. Preview
5. Move the cursor to the circumflex position `This is the ^**test**`
6. Preview

**Comment by efreykongcn** [comment]
This cursor issue had already been fixed in local. Now I've synchronized the code to GitHub.
