### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by shi131** [efreykongcn/NoteWidget#11]
It doesn't work after installation, there is this plugin in OneNote's add-ons, but even after enabling it, I can't see the markdown syntax even if I press F5, can you tell me about the installation precautions?

**Comment by superhu** [comment]
i found:right click and export to file (choose md format)

**Comment by efreykongcn** [comment]
This add-on is a markdown viewer to OneNote, it will add an sub-tab `Markdown` to `Home` tab in OneNote. 

The `Markdown` sub-tab includes 3 menu items: `Preview`, `Cheatsheet` and `Settings`.

After user created a new note based on markdown format, for example:

```markdown
# Mark down note example

## Sub-title
> quote
...

```

user clicks `Preview` menu button, this add-on will open the preview window to convert md format to html and preview the html page.

P.S.: Pressing `F5` cannot open preview window, and this add-on doesn't include features like converting other format into markdown.


Just like superhu's comment, this add-on also provides export features, user can right clicks on a note/book, and choose to export it into *.md file.
