### ISSUE TITLE
Invalid characters in page titles cause a trouble for Exporting Section to Hierarchial Files

### ISSUE THREAD

**Issue by seaspeak** [efreykongcn/NoteWidget#2]
NoteWidget won't generate hierarcial files, if their page titles contain invalid characters for Windows file names. I notice that you already deal with the issue when you export a single file, by replacing these invalid characters with "-". 

## Ref.
https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3
https://stackoverflow.com/a/12924582/5746539

**Comment by efreykongcn** [comment]
Fixed.
