### ISSUE TITLE
filename conflicts - "Export Section to Hierarchial Files"

### ISSUE THREAD

**Issue by seaspeak** [efreykongcn/NoteWidget#4]
Exported files with the same filenames in the same section (directory) will overwrite each other. The filename should be appended an extra number e.g."filename (1)".

**Comment by efreykongcn** [comment]
Fixed. [285871d](https://github.com/efreykongcn/NoteWidget/commit/285871d79a783da1465dbfbb21dd439d8e7e39f0)
